// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV2Zh3pc4yJz3hANoHpmkjOtPir-zk6a0',
    appId: '1:171963758250:web:2b7ae5ea0b91cd9e0982d3',
    messagingSenderId: '171963758250',
    projectId: 'fir-auth-19e30',
    authDomain: 'fir-auth-19e30.firebaseapp.com',
    storageBucket: 'fir-auth-19e30.appspot.com',
    measurementId: 'G-BB01E1PJJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzF8nJHlcx_npCqZm8JGCsfuN6qTiVF8',
    appId: '1:171963758250:android:b1d59fc150628dfd0982d3',
    messagingSenderId: '171963758250',
    projectId: 'fir-auth-19e30',
    storageBucket: 'fir-auth-19e30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLV0UyCibEe8aElMuWmCJiZPfPA1zF5Yg',
    appId: '1:171963758250:ios:2ee52021c11fc64b0982d3',
    messagingSenderId: '171963758250',
    projectId: 'fir-auth-19e30',
    storageBucket: 'fir-auth-19e30.appspot.com',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLV0UyCibEe8aElMuWmCJiZPfPA1zF5Yg',
    appId: '1:171963758250:ios:69923865f85876f60982d3',
    messagingSenderId: '171963758250',
    projectId: 'fir-auth-19e30',
    storageBucket: 'fir-auth-19e30.appspot.com',
    iosBundleId: 'com.example.rideShare.RunnerTests',
  );
}
